### PR TITLE
Update sqs.tf

### PR DESCRIPTION
**Pull request by b-geraghty**

### CODE REVIEW

**Comment by brendan-atlantis** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_sqs_queue.test-queue will be created
+ resource "aws_sqs_queue" "test-queue" {
      + arn                               = (known after apply)
      + content_based_deduplication       = false
      + deduplication_scope               = (known after apply)
      + delay_seconds                     = 0
      + fifo_queue                        = false
      + fifo_throughput_limit             = (known after apply)
      + id                                = (known after apply)
      + kms_data_key_reuse_period_seconds = (known after apply)
      + max_message_size                  = 262144
      + message_retention_seconds         = 345600
      + name                              = "test-queue"
      + name_prefix                       = (known after apply)
      + policy                            = (known after apply)
      + receive_wait_time_seconds         = 0
      + tags_all                          = (known after apply)
      + url                               = (known after apply)
      + visibility_timeout_seconds        = 30
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://c9b0-131-239-76-107.ngrok.io/lock?id=brendan-testing%252Ftesting%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by b-geraghty** [comment]
atlantis apply

**Comment by brendan-atlantis** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
```
exit status 1: running "terraform-wrapper apply" in "/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default": 
Not approved yet
environ({'REPO_REL_DIR': '.', 'HOSTNAME': '382a4912165b', 'SHLVL': '2', 'HOME': '/home/atlantis', 'COMMENT_ARGS': '', 'BASE_REPO_OWNER': 'brendan-testing', 'ATLANTIS_HOME': '/home/atlantis', 'ATLANTIS_REPO_CONFIG': '/home/atlantis/repos.yaml', 'WORKSPACE': 'default', 'DUMB_INIT_VERSION': '1.2.2', 'PULL_AUTHOR': 'b-geraghty', 'PROJECT_NAME': '', 'HEAD_REPO_OWNER': 'brendan-testing', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/atlantis/.atlantis/bin', 'PULL_NUM': '13', 'BASE_REPO_NAME': 'testing', 'DIR': '/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default', 'BASE_BRANCH_NAME': 'main', 'AWS_PROFILE': 'sandbox', 'HEAD_REPO_NAME': 'testing', 'GOSU_VERSION': '1.12', 'DEFAULT_TERRAFORM_VERSION': '0.13.0', 'PWD': '/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default', 'ATLANTIS_DEFAULT_TF_VERSION': '0.12.31', 'HEAD_BRANCH_NAME': 'b-geraghty-patch-3', 'PLANFILE': '/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default/default.tfplan', 'USER_NAME': 'b-geraghty', 'ATLANTIS_TERRAFORM_VERSION': '0.12.31'})


```

**Comment by b-geraghty** [comment]
atlantis plan

**Comment by brendan-atlantis** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_sqs_queue.test-queue will be created
+ resource "aws_sqs_queue" "test-queue" {
      + arn                               = (known after apply)
      + content_based_deduplication       = false
      + deduplication_scope               = (known after apply)
      + delay_seconds                     = 0
      + fifo_queue                        = false
      + fifo_throughput_limit             = (known after apply)
      + id                                = (known after apply)
      + kms_data_key_reuse_period_seconds = (known after apply)
      + max_message_size                  = 262144
      + message_retention_seconds         = 345600
      + name                              = "test-queue"
      + name_prefix                       = (known after apply)
      + policy                            = (known after apply)
      + receive_wait_time_seconds         = 0
      + tags_all                          = (known after apply)
      + url                               = (known after apply)
      + visibility_timeout_seconds        = 30
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://c9b0-131-239-76-107.ngrok.io/lock?id=brendan-testing%252Ftesting%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by b-geraghty** [comment]
atlantis apply

**Comment by brendan-atlantis** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
```
exit status 1: running "terraform-wrapper apply" in "/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default": 
Not approved yet
environ({'REPO_REL_DIR': '.', 'HOSTNAME': '525654c5bd60', 'SHLVL': '2', 'HOME': '/home/atlantis', 'COMMENT_ARGS': '', 'BASE_REPO_OWNER': 'brendan-testing', 'ATLANTIS_HOME': '/home/atlantis', 'ATLANTIS_REPO_CONFIG': '/home/atlantis/repos.yaml', 'WORKSPACE': 'default', 'DUMB_INIT_VERSION': '1.2.2', 'PULL_AUTHOR': 'b-geraghty', 'PROJECT_NAME': '', 'HEAD_REPO_OWNER': 'brendan-testing', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/atlantis/.atlantis/bin', 'PULL_NUM': '13', 'BASE_REPO_NAME': 'testing', 'DIR': '/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default', 'BASE_BRANCH_NAME': 'main', 'TEST': 'testing', 'AWS_PROFILE': 'sandbox', 'HEAD_REPO_NAME': 'testing', 'GOSU_VERSION': '1.12', 'DEFAULT_TERRAFORM_VERSION': '0.13.0', 'PWD': '/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default', 'ATLANTIS_DEFAULT_TF_VERSION': '0.12.31', 'PLANFILE': '/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default/default.tfplan', 'HEAD_BRANCH_NAME': 'b-geraghty-patch-3', 'USER_NAME': 'b-geraghty', 'ATLANTIS_TERRAFORM_VERSION': '0.12.31'})


```

**Comment by b-geraghty** [comment]
atlantis plan

**Comment by brendan-atlantis** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_sqs_queue.test-queue will be created
+ resource "aws_sqs_queue" "test-queue" {
      + arn                               = (known after apply)
      + content_based_deduplication       = false
      + deduplication_scope               = (known after apply)
      + delay_seconds                     = 0
      + fifo_queue                        = false
      + fifo_throughput_limit             = (known after apply)
      + id                                = (known after apply)
      + kms_data_key_reuse_period_seconds = (known after apply)
      + max_message_size                  = 262144
      + message_retention_seconds         = 345600
      + name                              = "test-queue"
      + name_prefix                       = (known after apply)
      + policy                            = (known after apply)
      + receive_wait_time_seconds         = 0
      + tags_all                          = (known after apply)
      + url                               = (known after apply)
      + visibility_timeout_seconds        = 30
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://c9b0-131-239-76-107.ngrok.io/lock?id=brendan-testing%252Ftesting%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by brendan-atlantis — APPROVED** [review]
LGTM

**Comment by b-geraghty** [comment]
atlantis apply

**Comment by brendan-atlantis** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
2022/07/13 16:08:19 [DEBUG] Using modified User-Agent: Terraform/0.12.31 Atlantis (brendan-testing/testing, PR#13, b-geraghty)
aws_sqs_queue.test-queue: Creating...
aws_sqs_queue.test-queue: Still creating... [10s elapsed]
aws_sqs_queue.test-queue: Still creating... [20s elapsed]
aws_sqs_queue.test-queue: Creation complete after 27s [id=https://sqs.us-east-1.amazonaws.com/402286737458/test-queue]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```
</details>

**Comment by brendan-atlantis** [comment]
atlantis plan

**Comment by b-geraghty** [comment]
atlantis plan

**Comment by b-geraghty** [comment]
atlantis plan

**Comment by b-geraghty** [comment]
atlantis plan

**Comment by b-geraghty** [comment]
atlantis plan

**Comment by brendan-atlantis** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
exit status 255: running "gcp_credentials_path.sh" in "/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default": 

An error occurred (AccessDeniedException) when calling the Decrypt operation: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.


```

**Comment by b-geraghty** [comment]
atlantis plan

**Comment by brendan-atlantis** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
exit status 255: running "gcp_credentials_path.sh" in "/home/atlantis/.atlantis/repos/brendan-testing/testing/13/default": 

An error occurred (AccessDeniedException) when calling the Decrypt operation: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.


```

**Pull request merged**
